version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: steam-analyser 
      DB_PORT: 5433
      DB_HOST: localhost
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    container_name: redis-steam-analyser
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata: