spring:
  profiles.active: ${PROFILE:dev}
  jpa:
    show-sql: true 
    database-platform: org.hibernate.dialect.PostgreSQLDialect
app:
  app-name: steam-analyser
  api-info:
    title: Steam Analyser